# Encoding

you know that model will train only on the numerical data it's not taking any categorical values only numerical \
so we have to convert the categorical data to numerical data 
thats why we have to use the concept of encoding

1. label encoding 
2. one hot endcoding
3. ordinal encoding

# label encoding 
    every number will get the number like 
    cat -- 0 dog -- 1 parrot -- 2
    this are the thing that you have 
    every category will get a unique number 
    but the problem is that model will more prefer who has 2 number 
    thats the biggest problem of label encoding thats why in production we are not using label encoding

In [1]:
import numpy as np
import pandas as pd

In [9]:
df = pd.read_csv('customer.csv')

In [10]:
df.sample(5)

    age  gender   review education purchased
2    70  Female     Good        PG        No
1    68  Female     Poor        UG        No
7    60  Female     Poor    School       Yes
34   86    Male  Average    School        No
28   48    Male     Poor    School        No

In [11]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [12]:
df = df.iloc[:,2:]

In [14]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,0:2], test_size=0.2, random_state=0)

In [16]:
X_train.shape

(40, 2)

In [17]:
X_test.shape

(10, 2)

In [27]:
df['review'].value_counts()

review
Poor       18
Good       18
Average    14
Name: count, dtype: int64

In [34]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

encoded = encoder.fit_transform(df['review'])

encoded

array([0, 2, 1, 1, 0, 0, 1, 2, 0, 1, 1, 1, 2, 0, 2, 2, 2, 2, 1, 2, 0, 0,
       2, 1, 0, 1, 2, 2, 2, 0, 0, 2, 0, 1, 0, 2, 1, 0, 1, 2, 1, 1, 1, 2,
       0, 2, 2, 1, 1, 1])

In [18]:
from sklearn.preprocessing import OneHotEncoder

In [19]:
encoder = OneHotEncoder()

In [28]:
encoded = encoder.fit_transform(df[['review']])

In [29]:
encoded.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

It reserves the natural order of the elements in the array for the purpose of keeping the data in a sorted order.

Since there is a natural ranking, assigning numbers makes sense.

yeh basically sensable order follow karta hai na ki label encoder jaise 

like jo natural existamce mein hai vaisa hi karta hia

In [35]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder()

In [36]:
encoded = encoder.fit_transform(df[['review']])

In [ ]:
encoded   # here it will be giving the natural existancing order

array([[0.],
       [2.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [1.],
       [1.],
       [2.],
       [0.],
       [2.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [0.],
       [0.],
       [2.],
       [1.],
       [0.],
       [1.],
       [2.],
       [2.],
       [2.],
       [0.],
       [0.],
       [2.],
       [0.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [2.],
       [0.],
       [2.],
       [2.],
       [1.],
       [1.],
       [1.]])

the usefulness of this system will depend upon the quality of the data

what the question will be demanding from ur side 

it totally depends upon your data

In [ ]:
ohe = OneHotEncoder(
    drop='first',   # YOU KNOW OHE WILL CREATE N COLUMNS FOR N CATEGORIES, SO TO AVOID THE DUMMY VARIABLE TRAP WE DROP ONE COLUMN
    sparse_output=False, #ohe returns always sparse matrix -- non zero thatswhy its store only non zero values
    handle_unknown='ignore'
)

In [ ]:
# lets understand the ordinal encoding how the order will be decided 

from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder(categories=[['bad' , 'good' , 'very good' , 'execellent']]) # it will decide the order based on the categories 

encoder.fit_transform(df[['review']])

# Imputer

Now lets talking about the imputer like some time we misses some values in the data so we can use the imputer to fill missing value

In [38]:
from sklearn.impute import SimpleImputer

In [ ]:
imputer = SimpleImputer(strategy='mean'
                        # , fill_value='Unknown'
                        ) #strategy='median' , strategy='most_frequent'

In [ ]:
X = imputer.fit_transform(df[['age']]) #you can also done from the