# Encoding

you know that model will train only on the numerical data it's not taking any categorical values only numerical \
so we have to convert the categorical data to numerical data 
thats why we have to use the concept of encoding

1. label encoding 
2. one hot endcoding
3. ordinal encoding

# label encoding 
    every number will get the number like 
    cat -- 0 dog -- 1 parrot -- 2
    this are the thing that you have 
    every category will get a unique number 
    but the problem is that model will more prefer who has 2 number 
    thats the biggest problem of label encoding thats why in production we are not using label encoding

In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('customer.csv')

In [5]:
df.sample(5)

    age  gender   review education purchased
30   73    Male  Average        UG        No
10   98  Female     Good        UG       Yes
25   57  Female     Good    School        No
1    68  Female     Poor        UG        No
26   53  Female     Poor        PG        No

In [8]:
df.head()

  purchased
0        No
1        No
2        No
3        No
4        No